if [[ "$SSH_CONNECTION" != "yes" && "$MY_SSH_CONNECTION" != "yes" ]]; then
	while true; do
		echo -n "Do you want to attach to a tmux session? [y/n] "
		read yn
		case $yn in
			[Yy]* ) MY_SSH_CONNECTION="yes" tmux attach; break;;
			[Nn]* ) exit;;
			* ) echo "Please answer y/n (Yes or no.)";;
		esac
	done
fi
